### ISSUE TITLE
JS file corrupted

### ISSUE THREAD

**Issue by bahendri** [pbucher/django-bootstrap-datepicker#1]
When used out of the box I get a JS console error telling me datepicker is not a function. Dropping in the bootstrap-datepicker.js from the CDN (instead of using the one under /static) resolved the issue for me.

**Comment by bahendri** [comment]
Never mind. It was my fault, not the JS file's (which is identical to the copy on the CDN).

Looking at the rendered HTML, I saw a script tag under my form linking to the JS file so I assumed it was being loaded. 

It looks like that must not be the case. If I manually add a <script> tag to the JS file in my base template everything works as expected.

**Comment by bahendri** [comment]
...and after further testing, the problem seems to be that my main bootstrap.js file was being loaded at the end of the document, after bootstrap-datepicker.js.

Moving bootstrap.js to the head seems to make the script under the form tag load correctly, voiding the need to hard-code the datepicker JS file into my base.

**Comment by pbucher** [comment]
Thanks for the feedback. I'll update the documentation with an example html base template to help folks going forward.
