### ISSUE TITLE
JSFiles object is not reversible

### ISSUE THREAD

**Issue by monim67** [pbucher/django-bootstrap-datepicker#12]
In DJango 2.0, `JSFiles` object needs to be reversible, otherwise it raises an error

> TypeError at /some_url
> 'JSFiles' object is not reversible

The issue can be solved by either renaming the `__iter__` method to `__reversed__` or by adding a `__reversed__` method to `JSFiles` Object. Adding a method instead of renaming keeps backward compatibility.

**Comment by pbucher** [comment]
Thanks for your PR. I didn't merge it because I had previously merged another PR to cover Django 1.11. I'm also in the process of some basic house keeping on this.
