### ISSUE TITLE
Django 1.11 issue

### ISSUE THREAD

**Issue by TheCthulhuKid** [pbucher/django-bootstrap-datepicker#3]
At least I think it is a 1.11 issue.

When trying to use the widget as is I got an `unexpected argument` exception on the line
`input_attrs = self.build_attrs(attrs, type=self.input_type, name=name)`

I fixed it by adding the `type` and `name` to the `attrs` manually beforehand.

**Comment by pbucher** [comment]
Fixed has been merged and a new release is in process.
